# [Template] Builds and publishes UPM .tgz packages
parameters:
  version: $(MRTKVersion)
  buildNumber: $(Build.BuildNumber)

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.18.0'
- task: PowerShell@2
  displayName: 'Build UPM packages'
  inputs:
    targetType: filePath
    filePath: ./scripts/packaging/createupmpackages.ps1
    arguments: >
      -ProjectRoot $(Get-Location)
      -OutputDirectory $(Build.ArtifactStagingDirectory)\build\upm\output
      -Version ${{ parameters.version }}
      -BuildNumber ${{ parameters.buildNumber }}
- task: PublishBuildArtifacts@1
  displayName: 'Publish UPM packages'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)\build\upm\output'
    ArtifactName: 'mrtk-upm'

